### ISSUE TITLE
documentation 

### ISSUE THREAD

**Issue by Rajeswari543** [AvinashSingh786/Fraud-Analysis#6]
please upload any documentation is their in the project and some errors in their executing the project and i request to clarify the doubts and ... please put the execution process and with the help of screen shorts....
                                 thank you

**Comment by AvinashSingh786** [comment]
Okay, I am not sure what more documentation you want. The installation process is defined and how to execute it as well. You need to have python installed and then run the python command "pip install -r requirements.txt" to install all dependencies and thereafter you can run each phase with the respective scripts. The code is documented and is easy to understand! There is no need for screenshots since they will differ. What errors are you getting?

**Comment by AvinashSingh786** [comment]
Closing this issue because of no response.
